name: apt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_2
  - pip=24.0=py39h06a4308_0
  - python=3.9.19=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=69.5.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.43.0=py39h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.21.0
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - anyio==4.4.0
      - async-timeout==4.0.3
      - attrs==23.2.0
      - certifi==2024.6.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cmake==3.29.3
      - contourpy==1.2.1
      - cupy-cuda12x==13.1.0
      - cycler==0.12.1
      - datasets==2.19.2
      - deepspeed==0.14.2
      - dill==0.3.8
      - distro==1.9.0
      - exceptiongroup==1.2.1
      - fastrlock==0.8.2
      - filelock==3.14.0
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - huggingface-hub==0.23.2
      - idna==3.7
      - immutabledict==4.2.0
      - importlib-resources==6.4.0
      - install==1.3.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.5
      - lit==18.1.6
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - mpmath==1.3.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - networkx==3.2.1
      - ninja==1.11.1.1
      - nltk==3.8.1
      - numpy==1.26.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.5.40
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.1.105
      - openai==0.28.0
      - ortools==9.6.2534
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - protobuf==5.27.0
      - psutil==5.9.8
      - py-cpuinfo==9.0.0
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - pydantic==2.7.3
      - pydantic-core==2.18.4
      - pynvml==11.5.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - pyyaml==6.0.1
      - regex==2024.5.15
      - requests==2.32.3
      - rouge-score==0.1.2
      - safetensors==0.4.3
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - six==1.16.0
      - sniffio==1.3.1
      - sympy==1.12.1
      - threadpoolctl==3.5.0
      - tokenizers==0.13.3
      - torch==2.0.1
      - tqdm==4.66.4
      - transformers==4.33.1
      - triton==2.0.0
      - typing-extensions==4.12.1
      - tzdata==2024.1
      - urllib3==2.2.1
      - xxhash==3.4.1
      - yarl==1.9.4
      - zipp==3.19.1
prefix: /home/bowen/miniconda3/envs/apt
